### ISSUE TITLE
not quite a pull request, feedback request

### ISSUE THREAD

**Issue by thfield** [cjerdonek/sf-base-election-data#5]
On  my fork, branch "working" , and html file "test.html" I've applied a lot of bootstrap styling to make navigation easier.  We had discussed some of this a while ago, and I just wanted to see if this what you had in mind before I go about diving into the python code for html generation

**Comment by cjerdonek** [comment]
Hi @thfield, thanks. Is there a way I could view it (e.g. by you pushing the site to your gh-pages branch)?

**Comment by thfield** [comment]
Ok, @cjerdonek got it working on gh-pages: http://thfield.github.io/sf-base-election-data/test.html

**Comment by cjerdonek** [comment]
Cool, that looks great!  I'm not quite sure yet how to manage modifications to the web site (especially large ones), and also given that the Python is still a bit in flux.  Maybe we can talk about it in person sometime.  Can you shoot me an e-mail just so I can be sure I have yours?  I don't think I have it.  Mine is listed at the bottom of the README of this repo.

Ideally, perhaps the Python code could remain the same or nearly the same, and the Django templates alone could be modified to allow experimenting with different layouts.  Also, just as an FYI, I'm thinking about breaking the HTML-generation code into a separate repo, so that the JSON file and the code to generate the JSON will be in one repo, and code that uses the JSON to generate HTML will be in a different one.  However, that change is probably at least a month away though.

**Comment by cjerdonek** [comment]
Closing this since we discussed in person.
